# Site settings
title: Greg Jolley -- Amp project
email: greg.s.jolley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Projects by Greg Jolley. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/amplifier" # the subpath of your site, e.g. /blog/
url: "http://gregjolley.github.io" # the base hostname & protocol for your site
github_username:  gregjolley

# Build settings
markdown: kramdown
